export const data =
    {
        "companies": [
            {
                "id": 1,
                "name": "Acme Corp",
                "location": "Bengaluru",
                "industry": "Software",
                "employees": 120,
                "founded": 2010,
                "revenue": "₹45 Cr",
                "ceo": "Rajesh Kumar",
                "phone": "+91-80-2234-5678",
                "image": "https://images.pexels.com/photos/3182835/pexels-photo-3182835.jpeg",
                "website": "https://acme.com",
                "email": "info@acme.com",
                "description": "Acme Corp develops cutting-edge software solutions for enterprises worldwide. Specializing in cloud-based applications, AI integration, and enterprise resource planning systems.Acme Corp develops cutting-edge software solutions for enterprises worldwide. Specializing in cloud-based applications, AI integration, and enterprise resource planning systems.Acme Corp develops cutting-edge software solutions for enterprises worldwide. Specializing in cloud-based applications, AI integration, and enterprise resource planning systems.Acme Corp develops cutting-edge software solutions for enterprises worldwide. Specializing in cloud-based applications, AI integration, and enterprise resource planning systems.Acme Corp develops cutting-edge software solutions for enterprises worldwide. Specializing in cloud-based applications, AI integration, and enterprise resource planning systems.Acme Corp develops cutting-edge software solutions for enterprises worldwide. Specializing in cloud-based applications, AI integration, and enterprise resource planning systems.Acme Corp develops cutting-edge software solutions for enterprises worldwide. Specializing in cloud-based applications, AI integration, and enterprise resource planning systems.",
                "services": ["Cloud Solutions", "AI Integration", "ERP Systems", "Custom Software Development"],
                "certifications": ["ISO 9001", "ISO 27001", "CMMI Level 5"],
                "clients": 250,
                "rating": 4.5
            },
            {
                "id": 2,
                "name": "GreenFoods",
                "location": "Mumbai",
                "industry": "Food",
                "employees": 45,
                "founded": 2016,
                "revenue": "₹12 Cr",
                "ceo": "Priya Sharma",
                "phone": "+91-22-4567-8901",
                "image": "https://images.pexels.com/photos/3184430/pexels-photo-3184430.jpeg",
                "website": "https://greenfoods.com",
                "email": "contact@greenfoods.com",
                "description": "GreenFoods specializes in organic and sustainable food products across India. Committed to promoting healthy living through pesticide-free, farm-fresh produce.",
                "services": ["Organic Produce", "Farm-to-Table Delivery", "Sustainable Farming Consultancy"],
                "certifications": ["USDA Organic", "India Organic", "Fair Trade"],
                "clients": 5000,
                "rating": 4.7
            },
            {
                "id": 3,
                "name": "BlueWave",
                "location": "Chennai",
                "industry": "Manufacturing",
                "employees": 300,
                "founded": 1998,
                "revenue": "₹200 Cr",
                "ceo": "Venkatesh Iyer",
                "phone": "+91-44-2890-1234",
                "image": "https://images.pexels.com/photos/3810792/pexels-photo-3810792.jpeg",
                "website": "https://bluewave.com",
                "email": "hello@bluewave.com",
                "description": "BlueWave is a leading manufacturer of industrial machinery and equipment. Known for precision engineering and innovative automation solutions.",
                "services": ["Industrial Machinery", "Automation Systems", "Custom Fabrication", "Maintenance Services"],
                "certifications": ["ISO 9001", "CE Certified", "BIS"],
                "clients": 180,
                "rating": 4.4
            },
            {
                "id": 4,
                "name": "FinSecure",
                "location": "Hyderabad",
                "industry": "Finance",
                "employees": 220,
                "founded": 2005,
                "revenue": "₹85 Cr",
                "ceo": "Anil Reddy",
                "phone": "+91-40-6789-0123",
                "image": "https://images.pexels.com/photos/4342493/pexels-photo-4342493.jpeg",
                "website": "https://finsecure.com",
                "email": "support@finsecure.com",
                "description": "FinSecure provides secure and reliable financial services to businesses and individuals. Specializing in wealth management, investment advisory, and digital banking solutions.Acme Corp develops cutting-edge software solutions for enterprises worldwide. Specializing in cloud-based applications, AI integration, and enterprise resource planning systems.Acme Corp develops cutting-edge software solutions for enterprises worldwide. Specializing in cloud-based applications, AI integration, and enterprise resource planning systems.Acme Corp develops cutting-edge software solutions for enterprises worldwide. Specializing in cloud-based applications, AI integration, and enterprise resource planning systems.Acme Corp develops cutting-edge software solutions for enterprises worldwide. Specializing in cloud-based applications, AI integration, and enterprise resource planning systems.",
                "services": ["Wealth Management", "Investment Advisory", "Digital Banking", "Insurance Services"],
                "certifications": ["RBI Licensed", "SEBI Registered", "ISO 27001"],
                "clients": 15000,
                "rating": 4.6
            },
            {
                "id": 5,
                "name": "EduAhead",
                "location": "Pune",
                "industry": "Education",
                "employees": 60,
                "founded": 2018,
                "revenue": "₹8 Cr",
                "ceo": "Sneha Deshmukh",
                "phone": "+91-20-3456-7890",
                "image": "https://images.pexels.com/photos/3184424/pexels-photo-3184424.jpeg",
                "website": "https://eduahead.com",
                "email": "info@eduahead.com",
                "description": "EduAhead offers innovative online learning platforms for students and professionals. Providing courses in technology, business, and creative skills.",
                "services": ["Online Courses", "Corporate Training", "Skill Development", "Certification Programs"],
                "certifications": ["NASSCOM Certified", "QCI Accredited"],
                "clients": 25000,
                "rating": 4.3
            },
            {
                "id": 6,
                "name": "AeroTech",
                "location": "Bengaluru",
                "industry": "Aerospace",
                "employees": 420,
                "founded": 2001,
                "revenue": "₹350 Cr",
                "ceo": "Captain Vikram Singh",
                "phone": "+91-80-5678-9012",
                "image": "https://images.pexels.com/photos/7078666/pexels-photo-7078666.jpeg",
                "website": "https://aerotech.com",
                "email": "contact@aerotech.com",
                "description": "AeroTech designs and manufactures advanced aerospace components and solutions. A trusted partner for defense and commercial aviation sectors.",
                "services": ["Aerospace Components", "Aircraft Maintenance", "Design Engineering", "R&D Services"],
                "certifications": ["AS9100", "NADCAP", "ISO 9001"],
                "clients": 45,
                "rating": 4.8
            },
            {
                "id": 7,
                "name": "HealthPlus",
                "location": "Delhi",
                "industry": "Healthcare",
                "employees": 150,
                "founded": 2012,
                "revenue": "₹65 Cr",
                "ceo": "Dr. Kavita Malhotra",
                "phone": "+91-11-7890-1234",
                "image": "https://images.pexels.com/photos/3758105/pexels-photo-3758105.jpeg",
                "website": "https://healthplus.com",
                "email": "info@healthplus.com",
                "description": "HealthPlus provides innovative healthcare solutions and medical services across India. Operating multi-specialty clinics and telemedicine platforms.",
                "services": ["Multi-Specialty Clinics", "Telemedicine", "Diagnostics", "Home Healthcare"],
                "certifications": ["NABH Accredited", "ISO 9001", "NABL"],
                "clients": 50000,
                "rating": 4.5
            },
            {
                "id": 8,
                "name": "Solaris",
                "location": "Ahmedabad",
                "industry": "Energy",
                "employees": 80,
                "founded": 2014,
                "revenue": "₹35 Cr",
                "ceo": "Arvind Patel",
                "phone": "+91-79-8901-2345",
                "image": "https://images.pexels.com/photos/1181346/pexels-photo-1181346.jpeg",
                "website": "https://solaris.com",
                "email": "contact@solaris.com",
                "description": "Solaris specializes in renewable energy solutions including solar and wind power. Committed to sustainable energy transition and carbon neutrality.",
                "services": ["Solar Installation", "Wind Energy", "Energy Consulting", "Grid Solutions"],
                "certifications": ["ISO 14001", "MNRE Approved", "BIS"],
                "clients": 320,
                "rating": 4.6
            },
            {
                "id": 9,
                "name": "UrbanMove",
                "location": "Mumbai",
                "industry": "Transportation",
                "employees": 200,
                "founded": 2013,
                "revenue": "₹95 Cr",
                "ceo": "Rahul Mehta",
                "phone": "+91-22-9012-3456",
                "image": "https://images.pexels.com/photos/3182755/pexels-photo-3182755.jpeg",
                "website": "https://urbanmove.com",
                "email": "info@urbanmove.com",
                "description": "UrbanMove provides innovative urban transportation solutions and smart mobility services. Integrating technology with sustainable transportation.",
                "services": ["Ride Sharing", "Fleet Management", "EV Charging Infrastructure", "Smart Parking"],
                "certifications": ["ISO 9001", "Carbon Neutral Certified"],
                "clients": 100000,
                "rating": 4.2
            },
            {
                "id": 10,
                "name": "CraftsPlus",
                "location": "Kochi",
                "industry": "Retail",
                "employees": 35,
                "founded": 2019,
                "revenue": "₹5 Cr",
                "ceo": "Maya Nair",
                "phone": "+91-484-0123-4567",
                "image": "https://images.pexels.com/photos/7688336/pexels-photo-7688336.jpeg",
                "website": "https://craftsplus.com",
                "email": "contact@craftsplus.com",
                "description": "CraftsPlus is a retail brand offering handmade and artisanal products for customers. Supporting local artisans and promoting traditional crafts.",
                "services": ["Handmade Products", "Custom Orders", "Artisan Workshops", "Online Store"],
                "certifications": ["Fair Trade", "Handicrafts Mark"],
                "clients": 8000,
                "rating": 4.7
            },
            {
                "id": 11,
                "name": "NextGen AI",
                "location": "Bengaluru",
                "industry": "AI",
                "employees": 500,
                "founded": 2020,
                "revenue": "₹120 Cr",
                "ceo": "Dr. Arjun Krishnan",
                "phone": "+91-80-1234-5678",
                "image": "https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg",
                "website": "https://nextgenai.com",
                "email": "info@nextgenai.com",
                "description": "NextGen AI develops cutting-edge artificial intelligence solutions for various industries. Specializing in machine learning, computer vision, and NLP.",
                "services": ["AI Consulting", "ML Model Development", "Computer Vision", "NLP Solutions"],
                "certifications": ["ISO 27001", "SOC 2", "GDPR Compliant"],
                "clients": 180,
                "rating": 4.9
            },
            {
                "id": 12,
                "name": "MediCare",
                "location": "Delhi",
                "industry": "Healthcare",
                "employees": 90,
                "founded": 2011,
                "revenue": "₹42 Cr",
                "ceo": "Dr. Sandeep Gupta",
                "phone": "+91-11-2345-6789",
                "image": "https://images.pexels.com/photos/7688173/pexels-photo-7688173.jpeg",
                "website": "https://medicare.com",
                "email": "support@medicare.com",
                "description": "MediCare provides advanced healthcare services and medical products for patients. Focus on affordable and accessible healthcare solutions.",
                "services": ["Medical Equipment", "Healthcare Services", "Patient Care", "Medical Supplies"],
                "certifications": ["NABH", "ISO 13485", "FDA Approved"],
                "clients": 35000,
                "rating": 4.4
            },
            {
                "id": 13,
                "name": "QuickMart",
                "location": "Mumbai",
                "industry": "Retail",
                "employees": 150,
                "founded": 2009,
                "revenue": "₹75 Cr",
                "ceo": "Suresh Jain",
                "phone": "+91-22-3456-7890",
                "image": "https://images.pexels.com/photos/7688174/pexels-photo-7688174.jpeg",
                "website": "https://quickmart.com",
                "email": "info@quickmart.com",
                "description": "QuickMart operates a chain of retail stores offering groceries and daily essentials. Known for quality products and excellent customer service.",
                "services": ["Grocery Retail", "Home Delivery", "Private Label Products", "Loyalty Programs"],
                "certifications": ["FSSAI Licensed", "ISO 22000"],
                "clients": 200000,
                "rating": 4.3
            },
            {
                "id": 14,
                "name": "BuildRight",
                "location": "Chennai",
                "industry": "Construction",
                "employees": 250,
                "founded": 1995,
                "revenue": "₹180 Cr",
                "ceo": "Sundar Raman",
                "phone": "+91-44-4567-8901",
                "image": "https://images.pexels.com/photos/3861970/pexels-photo-3861970.jpeg",
                "website": "https://buildright.com",
                "email": "contact@buildright.com",
                "description": "BuildRight is a construction company delivering high-quality infrastructure projects. Expertise in residential, commercial, and industrial construction.",
                "services": ["Residential Construction", "Commercial Projects", "Infrastructure", "Project Management"],
                "certifications": ["ISO 9001", "RERA Registered", "Green Building Certified"],
                "clients": 450,
                "rating": 4.5
            },
            {
                "id": 15,
                "name": "EcoWheels",
                "location": "Hyderabad",
                "industry": "Automotive",
                "employees": 300,
                "founded": 2017,
                "revenue": "₹150 Cr",
                "ceo": "Karthik Rao",
                "phone": "+91-40-5678-9012",
                "image": "https://images.pexels.com/photos/7120884/pexels-photo-7120884.jpeg",
                "website": "https://ecowheels.com",
                "email": "info@ecowheels.com",
                "description": "EcoWheels manufactures eco-friendly vehicles and automotive solutions. Leading the electric vehicle revolution in India.",
                "services": ["Electric Vehicles", "EV Components", "Charging Solutions", "After-Sales Service"],
                "certifications": ["ISO 9001", "ARAI Approved", "BIS"],
                "clients": 12000,
                "rating": 4.6
            },
            {
                "id": 16,
                "name": "BrightEdu",
                "location": "Pune",
                "industry": "Education",
                "employees": 75,
                "founded": 2016,
                "revenue": "₹18 Cr",
                "ceo": "Meera Kulkarni",
                "phone": "+91-20-6789-0123",
                "image": "https://images.pexels.com/photos/3182801/pexels-photo-3182801.jpeg",
                "website": "https://brightedu.com",
                "email": "contact@brightedu.com",
                "description": "BrightEdu offers innovative educational programs and e-learning platforms. Making quality education accessible to all.",
                "services": ["E-Learning Platform", "Test Preparation", "Career Counseling", "Skill Workshops"],
                "certifications": ["ISO 9001", "AICTE Approved"],
                "clients": 40000,
                "rating": 4.4
            },
            {
                "id": 17,
                "name": "FoodiesHub",
                "location": "Delhi",
                "industry": "Food",
                "employees": 60,
                "founded": 2018,
                "revenue": "₹22 Cr",
                "ceo": "Amit Verma",
                "phone": "+91-11-7890-1234",
                "image": "https://images.pexels.com/photos/6457515/pexels-photo-6457515.jpeg",
                "website": "https://foodieshub.com",
                "email": "info@foodieshub.com",
                "description": "FoodiesHub is a gourmet food delivery and catering service across Delhi. Specializing in multi-cuisine offerings and event catering.",
                "services": ["Food Delivery", "Catering Services", "Event Management", "Cloud Kitchen"],
                "certifications": ["FSSAI Licensed", "ISO 22000"],
                "clients": 30000,
                "rating": 4.5
            },
            {
                "id": 18,
                "name": "AgriGrow",
                "location": "Ahmedabad",
                "industry": "Agriculture",
                "employees": 110,
                "founded": 2002,
                "revenue": "₹55 Cr",
                "ceo": "Ramesh Patel",
                "phone": "+91-79-8901-2345",
                "image": "https://images.pexels.com/photos/3153199/pexels-photo-3153199.jpeg",
                "website": "https://agrigrow.com",
                "email": "contact@agrigrow.com",
                "description": "AgriGrow provides modern agricultural solutions and farming technologies. Empowering farmers with smart farming techniques and equipment.",
                "services": ["Smart Farming", "Agricultural Equipment", "Crop Advisory", "Irrigation Solutions"],
                "certifications": ["ISO 9001", "Agmark Certified"],
                "clients": 5500,
                "rating": 4.7
            },
            {
                "id": 19,
                "name": "LogiTrack",
                "location": "Mumbai",
                "industry": "Logistics",
                "employees": 400,
                "founded": 2007,
                "revenue": "₹280 Cr",
                "ceo": "Vijay Sharma",
                "phone": "+91-22-9012-3456",
                "image": "https://images.pexels.com/photos/5428826/pexels-photo-5428826.jpeg",
                "website": "https://logitrack.com",
                "email": "info@logitrack.com",
                "description": "LogiTrack offers logistics and supply chain management services globally. Providing end-to-end logistics solutions with real-time tracking.",
                "services": ["Supply Chain Management", "Warehousing", "Freight Forwarding", "Last Mile Delivery"],
                "certifications": ["ISO 9001", "AEO Certified", "GDP Certified"],
                "clients": 850,
                "rating": 4.6
            },
            {
                "id": 20,
                "name": "Cloudify",
                "location": "Bengaluru",
                "industry": "Cloud Services",
                "employees": 600,
                "founded": 2015,
                "revenue": "₹220 Cr",
                "ceo": "Sanjay Menon",
                "phone": "+91-80-0123-4567",
                "image": "https://images.pexels.com/photos/3182754/pexels-photo-3182754.jpeg",
                "website": "https://cloudify.com",
                "email": "support@cloudify.com",
                "description": "Cloudify provides cloud computing services and enterprise cloud solutions. Helping businesses migrate and manage their cloud infrastructure.",
                "services": ["Cloud Migration", "Cloud Management", "DevOps Services", "Cloud Security"],
                "certifications": ["ISO 27001", "SOC 2", "AWS Partner"],
                "clients": 420,
                "rating": 4.7
            },
            {
                "id": 21,
                "name": "TechNova",
                "location": "Bengaluru",
                "industry": "Software",
                "employees": 320,
                "founded": 2011,
                "revenue": "₹98 Cr",
                "ceo": "Deepak Agarwal",
                "phone": "+91-80-1234-5678",
                "image": "https://images.pexels.com/photos/3182831/pexels-photo-3182831.jpeg",
                "website": "https://technova.com",
                "email": "info@technova.com",
                "description": "TechNova develops custom software solutions for technology-driven businesses. Excellence in mobile apps, web applications, and blockchain solutions.",
                "services": ["Custom Software", "Mobile App Development", "Web Development", "Blockchain Solutions"],
                "certifications": ["ISO 9001", "CMMI Level 3", "ISO 27001"],
                "clients": 290,
                "rating": 4.5
            },
            {
                "id": 22,
                "name": "GreenEnergy",
                "location": "Ahmedabad",
                "industry": "Energy",
                "employees": 90,
                "founded": 2013,
                "revenue": "₹48 Cr",
                "ceo": "Jayesh Shah",
                "phone": "+91-79-2345-6789",
                "image": "https://images.pexels.com/photos/8378741/pexels-photo-8378741.jpeg",
                "website": "https://greenenergy.com",
                "email": "contact@greenenergy.com",
                "description": "GreenEnergy focuses on clean energy solutions and sustainable power projects. Pioneering renewable energy adoption in industrial sectors.",
                "services": ["Renewable Energy", "Energy Audit", "Power Purchase Agreements", "Energy Storage"],
                "certifications": ["ISO 14001", "MNRE Certified", "LEED Certified"],
                "clients": 280,
                "rating": 4.6
            },
            {
                "id": 23,
                "name": "SafeBank",
                "location": "Delhi",
                "industry": "Finance",
                "employees": 250,
                "founded": 2008,
                "revenue": "₹110 Cr",
                "ceo": "Ritu Khanna",
                "phone": "+91-11-3456-7890",
                "image": "https://images.pexels.com/photos/7552444/pexels-photo-7552444.jpeg",
                "website": "https://safebank.com",
                "email": "support@safebank.com",
                "description": "SafeBank offers a wide range of secure banking and financial services. Trusted by thousands for personal and business banking needs.",
                "services": ["Personal Banking", "Business Banking", "Loans", "Digital Payments"],
                "certifications": ["RBI Licensed", "PCI DSS", "ISO 27001"],
                "clients": 75000,
                "rating": 4.5
            },
            {
                "id": 24,
                "name": "DataCore",
                "location": "Pune",
                "industry": "Data Analytics",
                "employees": 180,
                "founded": 2019,
                "revenue": "₹52 Cr",
                "ceo": "Neha Kapoor",
                "phone": "+91-20-4567-8901",
                "image": "https://images.pexels.com/photos/3182835/pexels-photo-3182835.jpeg",
                "website": "https://datacore.com",
                "email": "info@datacore.com",
                "description": "DataCore specializes in big data analytics and business intelligence solutions. Helping organizations make data-driven decisions.",
                "services": ["Business Intelligence", "Data Analytics", "Predictive Modeling", "Data Visualization"],
                "certifications": ["ISO 27001", "SOC 2", "GDPR Compliant"],
                "clients": 160,
                "rating": 4.8
            },
            {
                "id": 25,
                "name": "AutoDrive",
                "location": "Chennai",
                "industry": "Automotive",
                "employees": 270,
                "founded": 2016,
                "revenue": "₹135 Cr",
                "ceo": "Ganesh Kumar",
                "phone": "+91-44-5678-9012",
                "image": "https://images.pexels.com/photos/3810792/pexels-photo-3810792.jpeg",
                "website": "https://autodrive.com",
                "email": "contact@autodrive.com",
                "description": "AutoDrive develops autonomous vehicle technologies and advanced driver assistance systems. Pioneering self-driving solutions for Indian roads.",
                "services": ["Autonomous Systems", "ADAS", "Vehicle Testing", "Software Integration"],
                "certifications": ["ISO 26262", "ASPICE", "ISO 9001"],
                "clients": 35,
                "rating": 4.7
            },
            {
                "id": 26,
                "name": "FreshFarm",
                "location": "Kochi",
                "industry": "Agriculture",
                "employees": 65,
                "founded": 2020,
                "revenue": "₹15 Cr",
                "ceo": "Thomas Joseph",
                "phone": "+91-484-6789-0123",
                "image": "https://images.pexels.com/photos/3184430/pexels-photo-3184430.jpeg",
                "website": "https://freshfarm.com",
                "email": "info@freshfarm.com",
                "description": "FreshFarm connects farmers directly with consumers through digital platforms. Ensuring fresh produce and fair prices for farmers.",
                "services": ["Direct Farm Sales", "Organic Produce", "Farm Management", "Market Linkage"],
                "certifications": ["Organic Certified", "FSSAI Licensed"],
                "clients": 12000,
                "rating": 4.6
            },
            {
                "id": 27,
                "name": "SmartHome",
                "location": "Bengaluru",
                "industry": "IoT",
                "employees": 140,
                "founded": 2017,
                "revenue": "₹38 Cr",
                "ceo": "Pooja Naik",
                "phone": "+91-80-7890-1234",
                "image": "https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg",
                "website": "https://smarthome.com",
                "email": "support@smarthome.com",
                "description": "SmartHome provides intelligent home automation and IoT solutions. Making homes smarter, safer, and more energy-efficient.",
                "services": ["Home Automation", "Smart Security", "Energy Management", "Voice Control"],
                "certifications": ["CE Certified", "RoHS", "BIS"],
                "clients": 18000,
                "rating": 4.5
            },
            {
                "id": 28,
                "name": "MediaWorks",
                "location": "Mumbai",
                "industry": "Media",
                "employees": 95,
                "founded": 2015,
                "revenue": "₹28 Cr",
                "ceo": "Kabir Malhotra",
                "phone": "+91-22-8901-2345",
                "image": "https://images.pexels.com/photos/7688336/pexels-photo-7688336.jpeg",
                "website": "https://mediaworks.com",
                "email": "contact@mediaworks.com",
                "description": "MediaWorks is a creative agency offering digital marketing and content production services. Crafting compelling brand stories.",
                "services": ["Digital Marketing", "Content Creation", "Video Production", "Social Media Management"],
                "certifications": ["Google Partner", "Facebook Blueprint"],
                "clients": 320,
                "rating": 4.4
            },
            {
                "id": 29,
                "name": "SecureNet",
                "location": "Hyderabad",
                "industry": "Cybersecurity",
                "employees": 210,
                "founded": 2014,
                "revenue": "₹72 Cr",
                "ceo": "Srinivas Reddy",
                "phone": "+91-40-9012-3456",
                "image": "https://images.pexels.com/photos/3182754/pexels-photo-3182754.jpeg",
                "website": "https://securenet.com",
                "email": "info@securenet.com",
                "description": "SecureNet provides comprehensive cybersecurity solutions for enterprises. Protecting organizations from evolving cyber threats.",
                "services": ["Security Audit", "Penetration Testing", "SOC Services", "Incident Response"],
                "certifications": ["ISO 27001", "CEH Certified", "CISA"],
                "clients": 240,
                "rating": 4.8
            },
            {
                "id": 30,
                "name": "PharmaCare",
                "location": "Delhi",
                "industry": "Pharmaceutical",
                "employees": 380,
                "founded": 2003,
                "revenue": "₹295 Cr",
                "ceo": "Dr. Ramesh Agrawal",
                "phone": "+91-11-0123-4567",
                "image": "https://images.pexels.com/photos/7688173/pexels-photo-7688173.jpeg",
                "website": "https://pharmacare.com",
                "email": "info@pharmacare.com",
                "description": "PharmaCare manufactures and distributes pharmaceutical products across India. Committed to affordable and quality healthcare.",
                "services": ["Generic Medicines", "OTC Products", "Contract Manufacturing", "R&D"],
                "certifications": ["WHO GMP", "ISO 9001", "FDA Approved"],
                "clients": 8500,
                "rating": 4.6
            },
            {
                "id": 31,
                "name": "TravelEasy",
                "location": "Mumbai",
                "industry": "Travel & Tourism",
                "employees": 125,
                "founded": 2018,
                "revenue": "₹45 Cr",
                "ceo": "Anjali Menon",
                "phone": "+91-22-1234-5678",
                "image": "https://images.pexels.com/photos/3182755/pexels-photo-3182755.jpeg",
                "website": "https://traveleasy.com",
                "email": "support@traveleasy.com",
                "description": "TravelEasy is a comprehensive travel booking platform for flights, hotels, and experiences. Making travel planning effortless.",
                "services": ["Flight Booking", "Hotel Reservations", "Tour Packages", "Travel Insurance"],
                "certifications": ["IATA Certified", "ISO 9001"],
                "clients": 150000,
                "rating": 4.5
            },
            {
                "id": 32,
                "name": "FitLife",
                "location": "Pune",
                "industry": "Fitness & Wellness",
                "employees": 85,
                "founded": 2019,
                "revenue": "₹18 Cr",
                "ceo": "Rohit Desai",
                "phone": "+91-20-2345-6789",
                "image": "https://images.pexels.com/photos/3758105/pexels-photo-3758105.jpeg",
                "website": "https://fitlife.com",
                "email": "info@fitlife.com",
                "description": "FitLife offers comprehensive fitness and wellness programs. Combining technology with personalized training for optimal health outcomes.",
                "services": ["Fitness Training", "Nutrition Consulting", "Wellness Programs", "Online Coaching"],
                "certifications": ["ISO 9001", "ACE Certified"],
                "clients": 22000,
                "rating": 4.7
            },
            {
                "id": 33,
                "name": "TextilePro",
                "location": "Ahmedabad",
                "industry": "Textile",
                "employees": 450,
                "founded": 2000,
                "revenue": "₹320 Cr",
                "ceo": "Hiren Modi",
                "phone": "+91-79-3456-7890",
                "image": "https://images.pexels.com/photos/3861970/pexels-photo-3861970.jpeg",
                "website": "https://textilepro.com",
                "email": "contact@textilepro.com",
                "description": "TextilePro is a leading textile manufacturer exporting to global markets. Specializing in sustainable and high-quality fabrics.",
                "services": ["Fabric Manufacturing", "Textile Exports", "Custom Designs", "Quality Testing"],
                "certifications": ["GOTS Certified", "OEKO-TEX", "ISO 9001"],
                "clients": 620,
                "rating": 4.5
            },
            {
                "id": 34,
                "name": "RoboTech",
                "location": "Bengaluru",
                "industry": "Robotics",
                "employees": 280,
                "founded": 2016,
                "revenue": "₹105 Cr",
                "ceo": "Dr. Pradeep Kumar",
                "phone": "+91-80-4567-8901",
                "image": "https://images.pexels.com/photos/7078666/pexels-photo-7078666.jpeg",
                "website": "https://robotech.com",
                "email": "info@robotech.com",
                "description": "RoboTech develops advanced robotics solutions for industrial and service applications. Leading innovation in automation and AI-powered robots.",
                "services": ["Industrial Robots", "Service Robots", "Automation Solutions", "Robot Training"],
                "certifications": ["ISO 9001", "CE Certified", "RIA Member"],
                "clients": 95,
                "rating": 4.8
            },
            {
                "id": 35,
                "name": "WaterPure",
                "location": "Chennai",
                "industry": "Water Treatment",
                "employees": 115,
                "founded": 2012,
                "revenue": "₹42 Cr",
                "ceo": "Lakshmi Iyer",
                "phone": "+91-44-5678-9012",
                "image": "https://images.pexels.com/photos/1181346/pexels-photo-1181346.jpeg",
                "website": "https://waterpure.com",
                "email": "contact@waterpure.com",
                "description": "WaterPure provides advanced water treatment and purification solutions. Ensuring access to clean and safe drinking water.",
                "services": ["Water Purification", "Sewage Treatment", "Industrial Water Treatment", "Maintenance"],
                "certifications": ["ISO 9001", "NSF Certified", "BIS"],
                "clients": 3200,
                "rating": 4.6
            },
            {
                "id": 36,
                "name": "GameZone",
                "location": "Hyderabad",
                "industry": "Gaming",
                "employees": 190,
                "founded": 2017,
                "revenue": "₹65 Cr",
                "ceo": "Karan Rao",
                "phone": "+91-40-6789-0123",
                "image": "https://images.pexels.com/photos/3182831/pexels-photo-3182831.jpeg",
                "website": "https://gamezone.com",
                "email": "support@gamezone.com",
                "description": "GameZone is a mobile gaming company creating engaging and addictive games. Reaching millions of players across India and globally.",
                "services": ["Game Development", "Publishing", "Live Operations", "Game Design"],
                "certifications": ["ISO 27001", "Google Play Partner"],
                "clients": 5000000,
                "rating": 4.4
            },
            {
                "id": 37,
                "name": "EcoPackaging",
                "location": "Mumbai",
                "industry": "Packaging",
                "employees": 160,
                "founded": 2015,
                "revenue": "₹58 Cr",
                "ceo": "Manish Joshi",
                "phone": "+91-22-7890-1234",
                "image": "https://images.pexels.com/photos/3153199/pexels-photo-3153199.jpeg",
                "website": "https://ecopackaging.com",
                "email": "info@ecopackaging.com",
                "description": "EcoPackaging manufactures sustainable and biodegradable packaging solutions. Helping brands reduce their environmental footprint.",
                "services": ["Eco-Friendly Packaging", "Custom Design", "Bulk Orders", "Consulting"],
                "certifications": ["FSC Certified", "ISO 14001", "Compostable Certified"],
                "clients": 780,
                "rating": 4.7
            },
            {
                "id": 38,
                "name": "LegalEase",
                "location": "Delhi",
                "industry": "Legal Services",
                "employees": 75,
                "founded": 2016,
                "revenue": "₹25 Cr",
                "ceo": "Adv. Neha Sharma",
                "phone": "+91-11-8901-2345",
                "image": "https://images.pexels.com/photos/7552444/pexels-photo-7552444.jpeg",
                "website": "https://legalease.com",
                "email": "contact@legalease.com",
                "description": "LegalEase provides comprehensive legal services and consultation. Simplifying legal processes for businesses and individuals.",
                "services": ["Legal Consultation", "Contract Drafting", "Compliance Services", "Litigation Support"],
                "certifications": ["Bar Council Registered", "ISO 9001"],
                "clients": 4500,
                "rating": 4.6
            },
            {
                "id": 39,
                "name": "SolarMax",
                "location": "Bengaluru",
                "industry": "Energy",
                "employees": 95,
                "founded": 2018,
                "revenue": "₹38 Cr",
                "ceo": "Suresh Babu",
                "phone": "+91-80-9012-3456",
                "image": "https://images.pexels.com/photos/8378741/pexels-photo-8378741.jpeg",
                "website": "https://solarmax.com",
                "email": "info@solarmax.com",
                "description": "SolarMax specializes in rooftop solar installations for residential and commercial properties. Making solar energy affordable and accessible.",
                "services": ["Rooftop Solar", "Solar Maintenance", "Energy Audit", "Battery Storage"],
                "certifications": ["MNRE Approved", "ISO 9001", "BIS"],
                "clients": 4200,
                "rating": 4.7
            },
            {
                "id": 40,
                "name": "VirtualSpace",
                "location": "Pune",
                "industry": "VR/AR",
                "employees": 105,
                "founded": 2019,
                "revenue": "₹32 Cr",
                "ceo": "Aditya Kulkarni",
                "phone": "+91-20-0123-4567",
                "image": "https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg",
                "website": "https://virtualspace.com",
                "email": "contact@virtualspace.com",
                "description": "VirtualSpace creates immersive VR and AR experiences for training, entertainment, and enterprise applications.",
                "services": ["VR Development", "AR Applications", "Training Simulations", "Virtual Events"],
                "certifications": ["ISO 9001", "Unity Certified"],
                "clients": 180,
                "rating": 4.6
            },
            {
                "id": 41,
                "name": "PetCare Plus",
                "location": "Kochi",
                "industry": "Pet Services",
                "employees": 48,
                "founded": 2020,
                "revenue": "₹9 Cr",
                "ceo": "Anitha Menon",
                "phone": "+91-484-1234-5678",
                "image": "https://images.pexels.com/photos/7688336/pexels-photo-7688336.jpeg",
                "website": "https://petcareplus.com",
                "email": "info@petcareplus.com",
                "description": "PetCare Plus offers comprehensive pet care services including grooming, veterinary care, and pet supplies.",
                "services": ["Pet Grooming", "Veterinary Services", "Pet Boarding", "Pet Supplies"],
                "certifications": ["Veterinary Council Registered"],
                "clients": 8500,
                "rating": 4.8
            },
            {
                "id": 42,
                "name": "ChemTech",
                "location": "Ahmedabad",
                "industry": "Chemicals",
                "employees": 340,
                "founded": 2004,
                "revenue": "₹245 Cr",
                "ceo": "Dharmesh Patel",
                "phone": "+91-79-2345-6789",
                "image": "https://images.pexels.com/photos/3810792/pexels-photo-3810792.jpeg",
                "website": "https://chemtech.com",
                "email": "contact@chemtech.com",
                "description": "ChemTech manufactures industrial chemicals and specialty compounds. Serving diverse industries with quality chemical solutions.",
                "services": ["Industrial Chemicals", "Custom Synthesis", "Chemical Trading", "Technical Support"],
                "certifications": ["ISO 9001", "ISO 14001", "REACH Compliant"],
                "clients": 520,
                "rating": 4.5
            },
            {
                "id": 43,
                "name": "SmartRetail",
                "location": "Mumbai",
                "industry": "Retail Tech",
                "employees": 135,
                "founded": 2018,
                "revenue": "₹48 Cr",
                "ceo": "Ravi Mehta",
                "phone": "+91-22-3456-7890",
                "image": "https://images.pexels.com/photos/7688174/pexels-photo-7688174.jpeg",
                "website": "https://smartretail.com",
                "email": "info@smartretail.com",
                "description": "SmartRetail provides technology solutions for modern retail operations. Helping retailers digitize and optimize their businesses.",
                "services": ["POS Systems", "Inventory Management", "Customer Analytics", "E-commerce Integration"],
                "certifications": ["ISO 27001", "PCI DSS"],
                "clients": 850,
                "rating": 4.4
            },
            {
                "id": 44,
                "name": "SkyDrone",
                "location": "Bengaluru",
                "industry": "Drones",
                "employees": 92,
                "founded": 2019,
                "revenue": "₹28 Cr",
                "ceo": "Vivek Sharma",
                "phone": "+91-80-4567-8901",
                "image": "https://images.pexels.com/photos/7078666/pexels-photo-7078666.jpeg",
                "website": "https://skydrone.com",
                "email": "contact@skydrone.com",
                "description": "SkyDrone manufactures commercial drones for agriculture, surveillance, and delivery applications.",
                "services": ["Drone Manufacturing", "Aerial Surveys", "Agricultural Drones", "Drone Training"],
                "certifications": ["DGCA Approved", "ISO 9001", "CE Certified"],
                "clients": 380,
                "rating": 4.7
            },
            {
                "id": 45,
                "name": "BioFuels",
                "location": "Chennai",
                "industry": "Bioenergy",
                "employees": 125,
                "founded": 2013,
                "revenue": "₹62 Cr",
                "ceo": "Selvam Raj",
                "phone": "+91-44-5678-9012",
                "image": "https://images.pexels.com/photos/1181346/pexels-photo-1181346.jpeg",
                "website": "https://biofuels.com",
                "email": "info@biofuels.com",
                "description": "BioFuels produces sustainable biofuels from agricultural waste and biomass. Contributing to India's clean energy goals.",
                "services": ["Biofuel Production", "Waste Management", "Energy Consulting", "R&D"],
                "certifications": ["ISO 14001", "BIS", "MNRE Approved"],
                "clients": 240,
                "rating": 4.6
            },
            {
                "id": 46,
                "name": "EventMaster",
                "location": "Delhi",
                "industry": "Event Management",
                "employees": 68,
                "founded": 2017,
                "revenue": "₹22 Cr",
                "ceo": "Priya Kapoor",
                "phone": "+91-11-6789-0123",
                "image": "https://images.pexels.com/photos/6457515/pexels-photo-6457515.jpeg",
                "website": "https://eventmaster.com",
                "email": "contact@eventmaster.com",
                "description": "EventMaster organizes corporate events, weddings, and social gatherings. Creating memorable experiences with attention to detail.",
                "services": ["Corporate Events", "Weddings", "Event Planning", "Venue Management"],
                "certifications": ["ISO 9001"],
                "clients": 1200,
                "rating": 4.7
            },
            {
                "id": 47,
                "name": "PrintPro",
                "location": "Hyderabad",
                "industry": "Printing",
                "employees": 88,
                "founded": 2010,
                "revenue": "₹35 Cr",
                "ceo": "Naresh Reddy",
                "phone": "+91-40-7890-1234",
                "image": "https://images.pexels.com/photos/3182835/pexels-photo-3182835.jpeg",
                "website": "https://printpro.com",
                "email": "info@printpro.com",
                "description": "PrintPro offers commercial printing services including offset, digital, and large format printing.",
                "services": ["Offset Printing", "Digital Printing", "Large Format", "Packaging Printing"],
                "certifications": ["ISO 9001", "FSC Certified"],
                "clients": 2400,
                "rating": 4.5
            },
            {
                "id": 48,
                "name": "InsureTech",
                "location": "Mumbai",
                "industry": "Insurance Tech",
                "employees": 155,
                "founded": 2018,
                "revenue": "₹58 Cr",
                "ceo": "Siddharth Jain",
                "phone": "+91-22-8901-2345",
                "image": "https://images.pexels.com/photos/4342493/pexels-photo-4342493.jpeg",
                "website": "https://insuretech.com",
                "email": "support@insuretech.com",
                "description": "InsureTech is a digital insurance platform making insurance accessible and affordable through technology.",
                "services": ["Insurance Comparison", "Policy Management", "Claims Processing", "Risk Assessment"],
                "certifications": ["IRDAI Licensed", "ISO 27001"],
                "clients": 85000,
                "rating": 4.4
            },
            {
                "id": 49,
                "name": "FurniCraft",
                "location": "Bengaluru",
                "industry": "Furniture",
                "employees": 145,
                "founded": 2014,
                "revenue": "₹52 Cr",
                "ceo": "Ramesh Kumar",
                "phone": "+91-80-9012-3456",
                "image": "https://images.pexels.com/photos/7688336/pexels-photo-7688336.jpeg",
                "website": "https://furnicraft.com",
                "email": "contact@furnicraft.com",
                "description": "FurniCraft designs and manufactures premium furniture for homes and offices. Combining traditional craftsmanship with modern design.",
                "services": ["Custom Furniture", "Office Furniture", "Interior Design", "Installation"],
                "certifications": ["ISO 9001", "FSC Certified"],
                "clients": 3800,
                "rating": 4.6
            },
            {
                "id": 50,
                "name": "FreshBrew",
                "location": "Kochi",
                "industry": "Food & Beverage",
                "employees": 52,
                "founded": 2019,
                "revenue": "₹14 Cr",
                "ceo": "Arjun Nair",
                "phone": "+91-484-0123-4567",
                "image": "https://images.pexels.com/photos/3184430/pexels-photo-3184430.jpeg",
                "website": "https://freshbrew.com",
                "email": "info@freshbrew.com",
                "description": "FreshBrew operates a chain of specialty coffee shops and roasts premium coffee beans. Bringing café culture to Kerala.",
                "services": ["Coffee Shops", "Coffee Roasting", "Franchise Opportunities", "Catering"],
                "certifications": ["FSSAI Licensed", "Fair Trade Certified"],
                "clients": 45000,
                "rating": 4.8
            }
        ]
    }